octopus:
  environments:
    - development
    - production
  development:
    shard_one:
      host: localhost
      adapter: postgresql
      database: mednet_development
      username: postgres
      password: 'hlk6'
      pool: 5
  production:
    shard_one:
      host: localhost
      adapter: postgresql
      database: mednet_development
      username: postgres
      password: '123123'
